### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by jabirmayar** [devyuji/isave_flutter#4]
When pasting url of post it gives error: 
`something went wrong! #FETCH POST`
Same with Profile fetching: 
`something went wrong! #Fetch Profile`

**Comment by jabirmayar** [comment]
yeah, but it would be great if you can just put me in the right direction. Thank you

**Comment by devyuji** [comment]
Well the API is build by me only. But I have been working on making a public API for instagram.
