### ISSUE TITLE
Get post doesnt work.

### ISSUE THREAD

**Issue by amini-reza** [devyuji/isave_flutter#6]
the released version that you posted does work but the code doesn't work.
When i looked into your code i couldn't figure out what are you doing
![Screen Shot 1400-12-17 at 12 34 07](https://user-images.githubusercontent.com/54965892/157204651-4db6c0d2-b7e8-4c92-8fc4-3f0e864e579f.png)
Why are you making request to an empty string?
I need to know how to get a post media link from Instagram for a college project. So i would really appreciate your help.

**Comment by devyuji** [comment]
I am making a api call over there.

Api is build by me only but that is not open source
